/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0a0e16',
        'surface-container-low': '#181c24',
        'surface-container': '#1c2028',
        'surface-container-high': '#262a33',
        'surface-container-highest': '#31353e',
        'surface': '#0f131c',
        'surface-dim': '#0f131c',
        'surface-bright': '#353942',
        'surface-variant': '#31353e',
        'surface-tint': '#d2bbff',
        'background': '#0f131c',
        'on-background': '#dfe2ee',
        'on-surface': '#dfe2ee',
        'on-surface-variant': '#ccc3d8',
        'inverse-surface': '#dfe2ee',
        'inverse-on-surface': '#2c3039',
        'primary': '#d2bbff',
        'primary-container': '#7c3aed',
        'on-primary': '#3f008e',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#732ee4',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        'secondary': '#4cd7f6',
        'secondary-container': '#03b5d3',
        'on-secondary': '#003640',
        'on-secondary-container': '#00424e',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-fixed': '#001f26',
        'on-secondary-fixed-variant': '#004e5c',
        'tertiary': '#4edea3',
        'tertiary-container': '#007650',
        'on-tertiary': '#003824',
        'on-tertiary-container': '#76ffc2',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'outline': '#958da1',
        'outline-variant': '#4a4455',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1.5rem',
        'gutter-mobile': '0.75rem',
        'margin': '2rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        'display': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-pill': ['Inter', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
        'readout-num': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display': ['3.75rem', { lineHeight: '1.05', letterSpacing: '-0.035em', fontWeight: '800' }],
        'display-mobile': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.025em', fontWeight: '800' }],
        'headline-xl': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-xl-mobile': ['1.75rem', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['1.5rem', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['1.25rem', { lineHeight: '1.35', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['0.9375rem', { lineHeight: '1.55', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'label-mono': ['0.6875rem', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '500' }],
        'label-pill': ['0.75rem', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
        'readout-num': ['0.875rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      }
    },
  },
  plugins: [],
}
